### ISSUE TITLE
LOL SKID

### ISSUE THREAD

**Issue by ghost** [scandalized/Discord-QR-Bot-Token-Logger-#1]
WHY DID U TRY AND STEAL MY SHIT

**Comment by ulnk** [comment]
THIS IS SO OBVIOUS THE README IS THE EXACT SAME

**Comment by ulnk** [comment]
DONT USE THIS GUYS BOT
ITS PROBABLY A TOKEN LOGGER

**Comment by ulnk** [comment]
DIDNT EVEN STAR MINE BOZO
